index.css, index.html
Made Home Page Responsive
Issue : #1 
@arpit456jain
=> Made Home Page Responsive

bootstrap/bootstrap.css, bootstrap/bootstrap.html
Please Review
https://user-images.githubusercontent.com/64218887/146720195-a352cd38-1e5a-4829-a297-66c829d84331.mp4
=> fixed responsivness of bootstrap page

Pricing/pricing.css, Pricing/pricing.html
Please Review
https://user-images.githubusercontent.com/64218887/146735552-73c0c25f-7a40-4cc3-857a-f7353462ae8e.mp4
=> fixed responsiveness of pricing page

Html/html.css, Html/html.html
=> Fixed Responsiveness of Html Page

Html/Style/style.css, Html/Style/style.html
Hey @arpit456jain
Please Review
=> Fixed Responsiveness of HTML->STYLES & SEMANTICS

Html/Lists/list.css, Html/Lists/list.html
Hey @arpit456jain
Please Review
=> Fixed Responsiveness of HTML->LIST

Html/Links/link.css, Html/Links/link.html
=> Fixed Responsiveness of HTML->LINK

Html/Images/Images.css, Html/Images/images.html
=> Fixed Responsiveness of HTML->IMAGE

Html/Basic/Basic.css, Html/Basic/Basic.html
=> Fixed Responsivness of HTML->BASIC

Python/Basic/Basic.css, Python/Basic/Basic.html, Python/Conditions/condition.css, Python/Conditions/condition.html, Python/DataTypes/datatypes.css, Python/DataTypes/datatypes.html, Python/File Handling/file.css, Python/File Handling/file.html, Python/Functions/function.css, Python/Functions/function.html, Python/Loop/loop.css, Python/Loop/loop.html, Python/Operator/operator.css, Python/Operator/operator.html, Python/RegEx/regex.css, Python/RegEx/regex.html, Python/python.css, Python/python.html, index.html
=> Added python course

README.md
=> Added Contributor and Admin in README.md

README.md
1. Fixed the alignment of the title "CodingEasy" to the center position.
2. Fixed the navigable links of table of contents.
3. Added the "Total Lines" badge, "Stars" badge, "Forks" badge, "Contributors", "Repo Size" and "last commit" badge for visitors to access the stats of the project.
4. Removed Emojis for better UI.
@arpit456jain Please review the changes and merge it if you find them suitable to be added to your project.
The sample Readme looks as follows:
=> Updated Readme.md file for UI enhancement

README.md
=> Added SWOC LOGO 

Html/Basic/Basic.html, Html/Images/images.html, Html/Links/link.html, Html/Lists/list.html, Html/Style/style.html, Html/Table/table.html, Html/html.html, Pricing/pricing.html, bootstrap/bootstrap.html, common.css, css/allign/allign.html, css/basic/basic.css, css/basic/basic.html, css/color/color.html, css/css.html, css/font/font.html, css/functions/functions.html, css/properties/properties.html
Fix : #49 
Hey @ankitapuri @LegendSumeet Please Review
=> Added Common CSS File

Features/features.css, Features/features.html, Python/Basic/Basic.html, Python/Conditions/condition.css, Python/Conditions/condition.html, Python/DataTypes/datatypes.html, Python/File Handling/file.html, Python/Functions/function.html, Python/Loop/loop.html, Python/Operator/operator.html, Python/RegEx/regex.html, Python/python.css, Python/python.html, javascr/datatypes/datatypes.html, javascr/events/events.html, javascr/functions/functions.html, javascr/javascr.html, javascr/jsclasses/jsclasses.html, javascr/jsconditions/jsconditions.html, javascr/jserrors/jserrors.html, javascr/jsmath/jsmath.html, javascr/jsnumbers/jsnumbers.html, javascr/objects/objects.html, javascr/operators/operators.html, javascr/string/string.html, javascr/syntax/syntax.html
Fix : #61 
Hey @ankitapuri @LegendSumeet 
Please Review
=> Linked Common Css For Js Py and Features

bootstrap/bootstrap.html, bootstrap/button/button.html, bootstrap/cards/cards.html, bootstrap/carousel/carousel.html, bootstrap/color/color.html, bootstrap/container/container.html, bootstrap/grid/grid.html, bootstrap/jumbotron/jumbotron.html, bootstrap/modal/modal.html, bootstrap/navbar/navbar.html
=> Added Complete Bootstrap Materials

javascr/events/events.html, javascr/functions/functions.html, javascr/jsclasses/jsclasses.html, javascr/jsconditions/jsconditions.html, javascr/jserrors/jserrors.html, javascr/objects/objects.html, javascr/string/string.html
=> Added JS Materials

Python/Basic/Basic.html, Python/DataTypes/datatypes.html, Python/Functions/function.html, Python/Operator/operator.html
Added Content in Datatype,operator, functions and PY basic
Fix : #56 
Please Review
=> Added Content in 4 Topics of PY

Python/Conditions/condition.css, Python/Conditions/condition.html, Python/File Handling/file.html, Python/Loop/loop.html, Python/RegEx/regex.html
=> Added Content in Remaining 4 Topics of PY

Auth/admin.py, Auth/apps.py, Auth/models.py, Auth/tests.py, Auth/urls.py, Auth/views.py, CodingEasy/settings.py, CodingEasy/urls.py, DashBoard/admin.py, DashBoard/apps.py, DashBoard/models.py, DashBoard/tests.py, DashBoard/urls.py, DashBoard/views.py, Home/admin.py, Home/apps.py, Home/models.py, Home/tests.py, Home/urls.py, Home/views.py
Hey @7saikat7 @arpit456jain 
Please review
Fix : #83
=> Added 3 Apps

Auth/admin.py, Auth/apps.py, Auth/models.py, Auth/tests.py, Auth/urls.py, Auth/views.py, CodingEasy/settings.py, CodingEasy/urls.py, DashBoard/admin.py, DashBoard/apps.py, DashBoard/models.py, DashBoard/tests.py, DashBoard/urls.py, DashBoard/views.py, Home/admin.py, Home/apps.py, Home/models.py, Home/tests.py, Home/urls.py, Home/views.py
Reverts arpit456jain/CodingEasy#95
please run it locally first, then create a PR
=> Revert "Added 3 Apps"

CodingEasy/forms.py, CodingEasy/urls.py, CodingEasy/views.py, templates/Login/login.html, templates/index.html
Hey @arpit456jain @7saikat7 
I have added code for login and signup as said by @arpit456jain 
but still my git is unable to detect the older files
for which i made 3 apps
=> Added Code for Login/Signup

Auth/admin.py, Auth/apps.py, Auth/models.py, Auth/tests.py, Auth/urls.py, Auth/views.py, CodingEasy/settings.py, CodingEasy/urls.py, DashBoard/admin.py, DashBoard/apps.py, DashBoard/models.py, DashBoard/tests.py, DashBoard/urls.py, DashBoard/views.py, Home/admin.py, Home/apps.py, Home/models.py, Home/tests.py, Home/urls.py, Home/views.py, templates/Login/login.html
Fix : #83 
Hey @arpit456jain @7saikat7 @Snehaa1203 
Please Review
=> Added Auth,DashBoard,Home Apps

templates/CPP/cpp.html
Please Review
The Preloader was made active in last PR made to cpp page
=> Removed Preloader From CPP Page

static/css/contact/contact.css, static/js/contact/contact.js, templates/contact/contact.html
=> Added Contact Us Page

CodingEasy/settings.py, DashBoard/admin.py, DashBoard/models.py, requirements.txt
=> implement a download csv feature in admin panel for downloading the data as csv file

templates/home/base.html, templates/home/index.html
Added base template which can be inherited by other templates.
=> Added base template.

home/views.py, static/css/jQuery/jQuery.css, templates/home/jQuery/Attributes/attributes.html, templates/home/jQuery/Effects/effects.html, templates/home/jQuery/Events/events.html, templates/home/jQuery/ManipulatingDOM/ManipulatingDOM.html, templates/home/jQuery/jQuery.html
=> The last Part of jQuery course

README.md
- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.
=> Reorder step of 'How to Make a Pull Request?'

CodingEasy/settings.py, home/admin.py, home/forms.py, home/models.py, home/views.py, static/css/contact/contact.css, static/css/jQuery/jQuery.css, static/js/contact/contact.js, templates/home/base.html, templates/home/contact/contact.html, templates/home/index.html, templates/home/jQuery/Attributes/attributes.html, templates/home/jQuery/Effects/effects.html, templates/home/jQuery/Events/events.html, templates/home/jQuery/ManipulatingDOM/ManipulatingDOM.html, templates/home/jQuery/jQuery.html
=> Contact us form

README.md
1. The links in the section "Table of Contents" in the file Readme.md was broken. So fixed it.
2. Links were redirecting to one of the repository i.e. Chayan-11 and not the owner of the repo 'arpit456jain' so I fixed them all, and now they direct shows the following content on clicking the link.
3. One of the link that is "Project Setup" was showing Error page not found on opening, so I fixed it, and now it shows the required project setup steps.
=> Broken Links Fixed

templates/home/ML/Support_Vector_Machines/Support_Vector_Machines.html
Image not found error is fixed by correcting image name in HTML file.
- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.
=> Image name fixed in SVM

templates/home/Python/File Handling/file.html
Removed br tag.
- [✔️] My code follows the code style of this project.
- [✔️] This PR does not contain plagiarized content.
- [✔️] The title of my pull request is a short description of the requested changes.
=> Indentation error fixed in file handling

README.md
=> Updating README.md file with the link of the CodingEasy repo

home/decorators.py, home/forms.py, home/urls.py, home/views.py, templates/home/Login/login.html, templates/includes/navbar.html
Closes #194 
Created new views for login, logout, and register for users using the inbuilt user model. Also changed navbar to add logout button if authenticated and changed login page to correct the register form.
=> [ADDED FEATURE] User Authentication System- Signin/Signup

home/views.py, static/css/navbar/navbar.css, templates/home/index.html, templates/includes/navbar.html
Closes #171 
- Added the option to view Courses from any page, as added option of Courses in Navbar.
- Removed bug, from the views.py file, as the rendered page location was given wrong.
- Updated navbar.css to update the styling of the newly made option of Courses.
=> Updated navbar -Issue #171

README.md
=> Changes in Mentor Section

templates/home/Git_GitHub/git.html
Closes #233 
A section has been added where You tube videos can be embedded
=> YouTube Video Embedded

static/css/index.css, static/css/navbar/navbar.css, templates/home/base.html, templates/home/index.html, templates/includes/footer.html, templates/includes/navbar.html
Improved  navbar and homepage
Closes #204 
changed color theme and style of home page (including navbar and footer)
1)
2)
=> Improved UI of Website

ML.txt
Link
https://drive.google.com/drive/u/0/folders/1cd-J8_d6fwlmoQyYsPrYruewp4zYegj0
=> Added 3 videos of which 2 videos length > 5 min in ML.txt

home/urls.py, home/views.py, static/json/content_writers.json, static/json/mentors.json, static/json/owners.json, static/json/top_contributors.json, static/json/video_creators.json, static/json/web_developers.json, team.json, templates/home/team/our_team.html, templates/includes/navbar.html
This is the pull request regarding issue #250 
I created a Our Team page that fetch data from JSON file and dynamically generate profile card on updating the JSON file.
Separate JSON files have been created for Owner, Mentor, Video Creators, Content Writers, Web Developers and Top Contributors in the static folder of this repo.
Profile cards are generated dynamically on updating JSON file of each.
Added Our Team tab in the navbar section.
=> Created a Our Team Page

templates/blog/base.html, templates/blog/blog-navbar.html, templates/users/profile.html
- search
- sidebar
- user profile
- reset the password and delete the account from the profile page
- add, update and delete a category 
- only the user who creates the post or category is able to edit or delete it
https://user-images.githubusercontent.com/56798376/166122223-016b8dc1-fa75-4c53-a448-82d8f7bdc4f6.mp4
=> The rest of coding easy blog features

static/json/content_writers.json, static/json/mentors.json, static/json/top_contributors.json, static/json/video_creators.json, static/json/web_developers.json, templates/home/team/our_team.html
This is the pull request regarding the issue #250 
Added details in the respective JSON file as per the information provided.
[![image](https://www.linkpicture.com/q/pr1_3.png)](https://www.linkpicture.com/view.php?img=LPic6272de579b595844565108)
[![image](https://www.linkpicture.com/q/pr2_1.png)](https://www.linkpicture.com/view.php?img=LPic6272de579b595844565108)
[![image](https://www.linkpicture.com/q/pr3.png)](https://www.linkpicture.com/view.php?img=LPic6272de579b595844565108)
=> Added details is JSON File

templates/home/ML/Linear_Regression/Linear_Regression.html
=> Updated Linear_Regression.html

templates/blog/blog-navbar.html, templates/blog/post_search_result.html, templates/includes/navbar.html
=> Updating search form and  search result page

templates/home/Python/Conditions/condition.html, templates/home/team/our_team.html
Replaced Facebook icon with the GitHub.
[![image](https://www.linkpicture.com/q/issue_295.png)](https://www.linkpicture.com/view.php?img=LPic62776b75823b02029003420)
=> Fixed bug in the team page

templates/home/Python/Conditions/condition.html, templates/home/Python/File Handling/file.html, templates/home/Python/Functions/function.html, templates/home/Python/Loop/loop.html, templates/home/base.html
This Pull Request is regarding issue #291 
I have embedded Python Replit IDE in the Functions, Loops, Conditional, and File Handling page.
[![image](https://www.linkpicture.com/q/ide_demo.png)](https://www.linkpicture.com/view.php?img=LPic62780c4b80e7a2142772534)
=> Embedded Python IDE

templates/home/CPP/Data_Types/data_types.html, templates/home/CPP/Loops/loops.html, templates/home/CPP/Operators/operators.html, templates/home/Python/DataTypes/datatypes.html, templates/home/Python/RegEx/regex.html, templates/home/javascr/functions/functions.html, templates/home/javascr/jsclasses/jsclasses.html, templates/home/javascr/jsconditions/jsconditions.html, templates/home/javascr/jserrors/jserrors.html, templates/home/javascr/jsmath/jsmath.html, templates/home/javascr/jsnumbers/jsnumbers.html, templates/home/javascr/objects/objects.html, templates/home/javascr/operators/operators.html, templates/home/javascr/string/string.html, templates/home/javascr/syntax/syntax.html
This Pull Request is regarding issue #291 
Embed IDE in JavaScript/Python/CPP pages for hands-on experience for the user.
[![image](https://www.linkpicture.com/q/cppide.png)](https://www.linkpicture.com/view.php?img=LPic627920cca01672113790190)
[![image](https://www.linkpicture.com/q/jside.png)](https://www.linkpicture.com/view.php?img=LPic627920cca01672113790190)
[![image](https://www.linkpicture.com/q/pythonide.png)](https://www.linkpicture.com/view.php?img=LPic627920cca01672113790190)
=> Embed IDE in JS/CPP/Python files

templates/home/C/Data_Types/data_types.html, templates/home/C/Variable_Types/Variable_Types.html, templates/home/C/arrays/arrays.html, templates/home/C/c.html, templates/home/C/descision-making/descision.html, templates/home/C/functions/functions.html, templates/home/C/loop-types/loops.html, templates/home/C/operators/operators.html, templates/home/C/strings/strings.html
This pull request is regarding issue #291 
Fixed URL routing in C language page that were previously redirecting to CPP pages.
Embedded IDE in C language pages
[![image](https://www.linkpicture.com/q/cpage.png)](https://www.linkpicture.com/view.php?img=LPic627ab3277bb1f10616323)
[![image](https://www.linkpicture.com/q/url_change.png)](https://www.linkpicture.com/view.php?img=LPic627ab3277bb1f10616323)
=> Fixed URL bug and embed IDE in C pages

templates/home/Html/Basic/Basic.html, templates/home/Html/Images/images.html, templates/home/Html/Links/link.html, templates/home/Html/Lists/list.html, templates/home/Html/Style/style.html, templates/home/Html/Table/table.html
This pullr request is regarding the issue #291 
Embedded IDEs in images tag page of HTML section.
[![image](https://www.linkpicture.com/q/Screenshot-from-2022-05-14-19-44-21.png)](https://www.linkpicture.com/view.php?img=LPic627fba98bd13e1602756085)
[![image](https://www.linkpicture.com/q/Screenshot-from-2022-05-14-20-00-17.png)](https://www.linkpicture.com/view.php?img=LPic627fbd3a4c694669324843)
=> IDE in HTML page

README.md
##⚒Fixes Issue
Closes #316 
Upstream URL made right in the readme
=> Documentation made right

templates/home/CPP/Data_Types/data_types.html
1.  Improves the formatting of the "Data-types" page of c++ course.
2.  Contributed with additional information about data types in c++ to improve the knowledge of the students.
3.  Formatted the code to improve the readability.
4.  Fixed the issue of Image not loading up.
Took reference of online learning resources to make sure authentic and verified information is provided to the learners.
=> updated doc for data-types

home/views.py, templates/home/CPP/decision/decision.html, templates/home/CPP/descition/descition.html, templates/home/CPP/functions/functions.html, templates/home/CPP/numbers/numbers.html
=> Added descison,functions &Numbers content in C++

templates/home/CPP/arrays/arrays.html, templates/home/CPP/pointers/pointers.html, templates/home/CPP/strings/strings.html
=> Added Content in arrays,pointers,strings in c++

static/json/top_contributors.json, static/json/web_developers.json, templates/home/team/our_team.html
=> Updating our team page

home/views.py, templates/quiz/result.html
Added answers of the respective questions in the Python Quiz result page
[![image](https://www.linkpicture.com/q/quizAnswers.png)](https://www.linkpicture.com/view.php?img=LPic628aac73d32131268917809)
=> Added answers section in Quiz Result Page

templates/home/C/arrays/arrays.html, templates/home/C/numbers/numbers.html, templates/home/C/strings/strings.html
=> Added Content in arrays,numbers,strings in C

templates/home/CPP/abstraction/abstraction.html, templates/home/CPP/class/class.html, templates/home/CPP/dynamic/dynamic.html, templates/home/CPP/encapsulation/encapsulation.html, templates/home/CPP/except/except.html, templates/home/CPP/inheritance/inheritance.html, templates/home/CPP/interfaces/interfaces.html, templates/home/CPP/namespaces/namespaces.html, templates/home/CPP/overloading/overloading.html, templates/home/CPP/polymorphism/polymorphism.html, templates/home/CPP/templates/templates.html
#360 
Added content to remaining 11 topics of C++ course -
Class & Objects , inheritance, overloading, polymorphism, abstraction, encapsulation, interfaces, exception handling, dynamic memory, namespaces, templates
=> Added content to remaining C++ topics

templates/home/Git_GitHub/advanced/advanced.html, templates/home/Git_GitHub/basic/basic.html, templates/home/Git_GitHub/intermediate/intermediate.html
=> Adding all videos to the Git & GitHub course

home/views.py, templates/home/css/basic/basic.html, templates/home/css/borders/borders.html, templates/home/css/boxModel/boxModel.html, templates/home/css/color/color.html, templates/home/css/comments/comments.html, templates/home/css/css.html
- CSS Comments
- CSS Borders
- CSS Box-Model &Outline
=> Adding new topics and edit old docs in CSS Course

Video tutorials by Tushar/Length of Last Word.txt, Video tutorials by Tushar/Palindrome Number.txt
=> Added 2 video solutions of leetcode

Video tutorials by Tushar/Add Digits.txt, Video tutorials by Tushar/Reverse Integer.txt
=> Added two video tutorials of leetcode

templates/home/bootstrap/bootstrap.html, templates/home/bootstrap/button/button.html, templates/home/bootstrap/cards/cards.html, templates/home/bootstrap/carousel/carousel.html, templates/home/bootstrap/color/color.html, templates/home/bootstrap/container/container.html, templates/home/bootstrap/grid/grid.html, templates/home/bootstrap/jumbotron/jumbotron.html, templates/home/bootstrap/modal/modal.html, templates/home/bootstrap/navbar/navbar.html
Closes part of #391 
Added code editor in Bootstrap Course
The same way added for all the modules
=> Code editor added in Bootstrap

templates/home/CPP/Constants/Literals/Constants.html, templates/home/CPP/Data_Types/data_types.html, templates/home/CPP/Modifiers/modifiers.html, templates/home/CPP/Operators/operators.html, templates/home/CPP/Storage_Classes/storage_classes.html, templates/home/CPP/abstraction/abstraction.html, templates/home/CPP/arrays/arrays.html, templates/home/CPP/class/class.html, templates/home/CPP/decision/decision.html, templates/home/CPP/dynamic/dynamic.html, templates/home/CPP/encapsulation/encapsulation.html, templates/home/CPP/except/except.html, templates/home/CPP/functions/functions.html, templates/home/CPP/inheritance/inheritance.html, templates/home/CPP/interfaces/interfaces.html, templates/home/CPP/namespaces/namespaces.html, templates/home/CPP/numbers/numbers.html, templates/home/CPP/overloading/overloading.html, templates/home/CPP/pointers/pointers.html, templates/home/CPP/polymorphism/polymorphism.html, templates/home/CPP/strings/strings.html
Added IDEs in CPP files pages.
[![image](https://www.linkpicture.com/q/cppIde.png)](https://www.linkpicture.com/view.php?img=LPic628fbfa22f18c1244550047)
=> Added IDE in CPP files

home/urls.py, home/views.py, static/json/quizCategory.json, static/json/quizJSON/quizC.json, static/json/quizJSON/quizCpp.json, static/json/quizJSON/quizDjango.json, static/json/quizJSON/quizJs.json, templates/quiz/quizC.html, templates/quiz/quizCpp.html, templates/quiz/quizDjango.html, templates/quiz/quizJs.html
This Pll request is regarding the issue #412 
Added Quiz pages in C, Cpp, Js, and Django pages. With a dynamic result page with solutions
[![image](https://www.linkpicture.com/q/quizCPP.png)](https://www.linkpicture.com/view.php?img=LPic6290c99e512fd1290705484)
=> Added Quiz Pages in C/CPP/Js/Django Pages

templates/home/ML/Decision_Tree/Decision_Tree.html, templates/home/ML/Gridsearch/Gridsearch.html, templates/home/ML/Hierarchical Clustering/Hierarchical Clustering.html, templates/home/ML/K-Fold Cross Validation/K-Fold Cross Validation.html, templates/home/ML/K_Means_Clustering/K_Means_Clustering.html, templates/home/ML/K_Nearest_Neighbors/K_Nearest_Neighbors.html, templates/home/ML/Linear_Regression/Linear_Regression.html, templates/home/ML/Logistic_Regression/Logistical_Regression.html, templates/home/ML/ML.html, templates/home/ML/Naive_Bayes/Naive_Bayes.html, templates/home/ML/One Hot Encoding/One Hot Encoding.html, templates/home/ML/Random_Forest/Random_Forest.html, templates/home/ML/Support_Vector_Machines/Support_Vector_Machines.html
- K Nearest Neighbors
- Support Vector Machines
- Naive Bayes
- K Means Clustering
- Hierarchical Clustering
- One Hot Encoding
- K-Fold Cross-Validation
- Grid Search
=> Adding 31 videos to ML Course

templates/home/ML/Decision_Tree/Decision_Tree.html, templates/home/ML/Linear_Regression/Linear_Regression.html, templates/home/ML/Logistic_Regression/Logistical_Regression.html, templates/home/ML/ML.html, templates/home/ML/Random_Forest/Random_Forest.html
- The main page 
- Linear Regression
- Logistic Regression
- Decision Tree
- Random Forest
=> Adding 20 videos to ML Course in 5 topics and the main page of the Course

templates/home/Git_GitHub/advanced/advanced.html, templates/home/Git_GitHub/basic/basic.html, templates/home/Git_GitHub/intermediate/intermediate.html
This Pull request is regarding the issue #308 
Designed the Git and GitHub resources pages and add the missing videos
[![image](https://www.linkpicture.com/q/github_01.png)](https://www.linkpicture.com/view.php?img=LPic62927edad37c31397691577)
----
[![image](https://www.linkpicture.com/q/github_02.png)](https://www.linkpicture.com/view.php?img=LPic62927edad37c31397691577)
----
[![image](https://www.linkpicture.com/q/github_03.png)](https://www.linkpicture.com/view.php?img=LPic62927edad37c31397691577)
=> Design Github Pages and Add missing videos

templates/home/Html/Basic/Basic.html, templates/home/Html/Images/images.html, templates/home/Html/Links/link.html, templates/home/Html/Lists/list.html, templates/home/Html/Style/style.html, templates/home/Html/Table/table.html, templates/home/Html/html.html
=> Improving the code indentation in the html course and fix some syntax error in some codes

templates/home/Html/Basic/Basic.html, templates/home/Html/Images/images.html, templates/home/Html/Links/link.html, templates/home/Html/Lists/list.html, templates/home/Html/Style/style.html, templates/home/Html/Table/table.html, templates/home/Html/html.html
=> Adding all videos which have topics on Coding Easy website and the count of them = 20

Video tutorials by Tushar/Valid Anagram.txt, Video tutorials by Tushar/Valid Palindrome.txt
=> Added two video tutorials of youtube

Video tutorials/Django Tutorials/databsae django tutorial.txt, Video tutorials/LeetCode Problem Solutions/Add digits.txt
=> added aadDigits leetcode Video Tutorial, added django database tutorial

templates/home/Html/Lists/list.html, templates/home/Html/Style/style.html, templates/home/Html/Table/table.html
1. Lists
2. Tables
3. Styles and Semantics
=> Adding 9 videos to the html course in 3 topics

Video tutorials/LeetCode Problem Solutions/FindTheDuplicateNumber.cpp
Added video solution to Leetcode problem 287.
Added brute force as well as optimized solution.
Also added video solution explaining both the approaches.
Video Solution
=> Added video solution to Leetcode Q287

templates/home/Python/Basic/Basic.html, templates/home/Python/Exception/exception.html, templates/home/Python/Functional_Programming/functional_programming.html, templates/home/Python/OOP/oop.html, templates/home/Python/Operator/operator.html, templates/home/Python/Working_with_Strings/working_with_strings.html, templates/home/Python/python.html
Closes #443 
Adding code editors in python course done
=> Adding code editors in python course

Video tutorials/LeetCode Problem Solutions/SearchIn2DMatrix.cpp
I have added a video solution for leetcode question. 
And also explained 3 approaches for the question one brute force, one better and most optimal one.
Video Solution :
=> Added video solution for leetcode Q74

Video tutorials/LeetCode Problem Solutions/Group Anagrams.txt, Video tutorials/LeetCode Problem Solutions/Linked List Cycle.txt, Video tutorials/LeetCode Problem Solutions/Plus one.txt
=> Added 3 video tutorials of leetcode

home/urls.py, home/views.py, templates/home/Leetcode/LeetCode.html, templates/includes/navbar.html
=> LeetCode Videos

templates/home/Html/Style/style.html
=> Adding all the new HTML videos uploaded to YouTube
